/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppSelector {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface AppSelectorAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppSelector': Components.AppSelector;
  }

  interface StencilIntrinsicElements {
    'app-selector': Components.AppSelectorAttributes;
  }


  interface HTMLAppSelectorElement extends Components.AppSelector, HTMLStencilElement {}
  var HTMLAppSelectorElement: {
    prototype: HTMLAppSelectorElement;
    new (): HTMLAppSelectorElement;
  };

  interface HTMLElementTagNameMap {
    'app-selector': HTMLAppSelectorElement
  }

  interface ElementTagNameMap {
    'app-selector': HTMLAppSelectorElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
